### ISSUE TITLE
No module named 'datasets'

### ISSUE THREAD

**Issue by avoiteh** [EvilFreelancer/ruGPT-3.5-training#1]
I ask for help
During installation(windows 10), I somehow managed, but:
`(venv) c:\user\ruGPT-3.5-training-main>python 1_dataset.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\user\ruGPT-3.5-training-main\rulm\self_instruct\src\data_processing\create_chat_set.py", line 6, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
Traceback (most recent call last):
  File "c:\user\ruGPT-3.5-training-main\1_dataset.py", line 11, in <module>
    subprocess.run(
  File "C:\Users\Parser\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '-m', 'src.data_processing.create_chat_set', 'C:\\user\\ruGPT-3.5-training-main\\train_full.jsonl', 'C:\\user\\ruGPT-3.5-training-main\\val_full.jsonl']' returned non-zero exit status 1.
`
...I get the error No module named 'datasets' although there is such a module installed and it is visible through the pip list
I can't find a solution :(

**Comment by EvilFreelancer** [comment]
Привет!

Крайне любопытная ситуация, не вижу какая версия Python, поэтому предполагаю 3.12, однако, в момент написания статьи на Хабр об этом проекте у меня была 3.10 соответственно и версии пакетов я зафиксировал с учётом этой версии.

Могу предложить воспользоваться ею, а ещё все пакеты ставить при помощи virtual environment (в смысле `python3 -m venv venv` и так далее).

Либо есть ещё один вариант:
https://github.com/EvilFreelancer/saiga-custom/blob/main/rugpt35_13b.ipynb

В данном блокноте я чуть улучшил скрипты обучения из оригинальной статьи.

Ещё один вариант это: https://github.com/EvilFreelancer/impruver

Мой полный аналог скриптов обучения saiga или любой другой модели на любом другом наборе датасетов, хоть в lora хоть в полном формате.

**Comment by avoiteh** [comment]
Спасибо за ответ!
Питон 3.11
Попробую снести и поставить 3.10

Я, к сожалению, в питонах полный нуб - всю жизнь эмбед и веб

**Comment by avoiteh** [comment]
Переставил python 3.10
Увы :(

`(venv) c:\user\ruGPT-3.5-training-main>python 1_dataset.py
Traceback (most recent call last):
  File "C:\Users\Parser\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Parser\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\user\ruGPT-3.5-training-main\rulm\self_instruct\src\data_processing\create_chat_set.py", line 6, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'`

При этом:
`(venv) c:\user\ruGPT-3.5-training-main>pip list`

Возвращает:
`datasets           2.14.7`

P.S. Попробую Impruver

**Comment by EvilFreelancer** [comment]
Ну мы в чатике обсудили эту проблему, оказалось что дело в старой видеокарте GT710 на которую криво установилс Torch, плюс часть пакетов собрались с ошибками и так далее.
